#!/usr/bin/env python3
"""
TTW Football Intelligence Library — Phase 5 validation
=======================================================

Ten checks, one per owner-stated validation item. Any failure exits 1.

The adversarial checks matter more than the counting ones. Check 4 takes
the frozen workbook's own QB confidence codes and fails the build if any
appears in the Coaching Database, because the fastest way to corrupt a
frozen artefact is to quote it somewhere it does not belong. Check 6 takes
the Stability Score components straight from the extracted table and
re-reads them out of the rendered markdown, so a renderer that silently
recomputed a score would be caught rather than trusted.
"""

import glob
import hashlib
import json
import os
import re
import sys

from coach_lib import (NA, coaching_conflicts, load_carousel, load_details,
                       load_notes, load_stability, load_teams, slug)

OUT = "03_Coaching_Database"
FAIL = []
PASS = []

INDEXES = [
    "00_COACH_DIRECTORY.md", "00_CONTINUITY_MATRIX.md",
    "00_NEW_HEAD_COACHES.md", "00_NEW_OFFENSIVE_COORDINATORS.md",
    "00_NEW_DEFENSIVE_COORDINATORS.md", "00_NEW_PLAY_CALLERS.md",
    "00_MAJOR_SCHEME_CHANGES.md", "00_HIGH_CONTINUITY_STAFFS.md",
    "00_LOW_CONTINUITY_STAFFS.md", "00_QB_COACHING_CROSSLINK.md",
    "00_SOURCE_CONFLICTS.md", "README.md",
]


def check(ok, msg, detail=""):
    (PASS if ok else FAIL).append(msg + (f" — {detail}" if detail and not ok else ""))


def main():
    teams = load_teams()
    details = load_details()
    stability = load_stability()
    carousel = load_carousel()
    notes = load_notes()
    rows = {r["team"]: r for r in json.load(open("_source/data/coaching_matrix.json"))}

    files = {f for f in os.listdir(OUT)
             if f.endswith(".md") and not f.startswith("00_") and f != "README.md"}
    text = {t: open(os.path.join(OUT, slug(t))).read()
            for t in teams if os.path.exists(os.path.join(OUT, slug(t)))}

    # 1 -- every FBS team has a coaching record
    missing = sorted(t for t in teams if slug(t) not in files)
    check(len(files) == 138 and not missing,
          "all 138 teams have a coaching record",
          f"{len(files)} files; missing {missing[:5]}")

    # 2 -- all 29 fields present on every record
    bad = []
    for t, body in text.items():
        nums = set(re.findall(r"^\| (\d+) \| ", body, re.M))
        if len(nums) != 28 or "## 29. Cross-links" not in body:
            bad.append(f"{t}:{len(nums)}")
    check(not bad, "all 29 fields present on every record", str(bad[:5]))

    # 3 -- unaddressed fields carry the exact sentinel, never a guess
    guessy = re.compile(r"\b(unknown|n/?a|tbd|unclear|probably not addressed)\b",
                        re.I)
    bad = []
    for t, rec in notes.items():
        for k, v in rec.items():
            if isinstance(v, str) and v.strip() and v != NA and len(v) < 30 \
                    and guessy.search(v):
                bad.append(f"{t}.{k}")
    sentinel_used = sum(1 for rec in notes.values() for v in rec.values()
                        if v == NA)
    check(not bad and sentinel_used > 0,
          f"unaddressed fields use the literal sentinel ({sentinel_used} uses)",
          str(bad[:5]))

    # 4 -- the frozen v0.8.1 workbook is untouched and unquoted here
    inv = json.load(open("_source/verified/qb_inventory_v079.json"))
    digest = hashlib.sha256(
        open("_source/verified/qb_inventory_v079.json", "rb").read()).hexdigest()
    bleed = []
    for t, body in text.items():
        if re.search(r"\b(confidence code|H/M/L|v0\.8\.1|workbook)\b", body, re.I):
            bleed.append(t)
    check(not bleed and inv["counts"] == {"L": 33, "M": 40, "H": 65},
          f"frozen workbook untouched and unquoted (sha256 {digest[:16]}…)",
          str(bleed[:5]))

    # 5 -- no post-publication or outside-research language anywhere
    #
    # The renderer's own provenance banner contains the phrase "no
    # post-publication updates", so it has to come out before the scan or
    # every file matches. That is a validator artefact, not a defect in the
    # records; the banner text is generated by build_coaching.py and is
    # removed by exact match so a hand-edited variant would not slip past.
    BANNER = ("GUIDE CONTENT throughout. No outside research, and no "
              "post-publication updates: this record states the guide's "
              "position at publication and nothing later.")
    outside = re.compile(
        r"\b(as of (?:today|now|August|September)|per (?:ESPN\.com|247Sports\.com)"
        r"|according to reports this week|latest reports|post-publication"
        r"|updated since|since the guide (?:was )?(?:published|went to press))\b",
        re.I)
    bad = [t for t, body in text.items()
           if outside.search(body.replace(BANNER, ""))]
    check(not bad, "no post-publication or outside-research language", str(bad[:5]))

    # 6 -- Stability Score reproduced exactly, never recomputed
    bad = []
    for t, body in text.items():
        s = stability[t]
        want = [("Head coach returns", s["hc_returns"]),
                ("Offensive coordinator returns", s["oc_returns"]),
                ("Defensive coordinator returns", s["dc_returns"]),
                ("Quarterback returns", s["qb_returns"]),
                ("Returning starters", s["returning_starters_points"])]
        for label, pts in want:
            if f"| {label} | {pts} |" not in body:
                bad.append(f"{t}:{label}")
        if f"| **Total** | **{s['stability_score']}** |" not in body:
            bad.append(f"{t}:total")
        comp = (int(s["hc_returns"]) + int(s["oc_returns"]) + int(s["dc_returns"])
                + int(s["qb_returns"]) + int(s["returning_starters_points"]))
        if comp != int(s["stability_score"]):
            bad.append(f"{t}:sum{comp}!={s['stability_score']}")
    check(not bad, "printed Stability Score reproduced exactly on all 138",
          str(bad[:5]))

    # 7 -- no TTW-invented stability metric anywhere
    invented = re.compile(r"\b(TTW (?:stability|continuity) score|adjusted "
                          r"stability|recomputed|our stability)\b", re.I)
    bad = [f for f in list(files) + INDEXES
           if os.path.exists(os.path.join(OUT, f))
           and invented.search(open(os.path.join(OUT, f)).read())]
    check(not bad, "no TTW-invented stability metric", str(bad[:5]))

    # 8 -- change is never labelled good or bad by the library itself
    verdict = re.compile(r"\b(this (?:hire|change) (?:is|was) (?:a )?"
                         r"(?:good|bad|upgrade|downgrade)|clearly an upgrade "
                         r"for the programme|TTW rates this hire)\b", re.I)
    bad = []
    for f in INDEXES:
        p = os.path.join(OUT, f)
        if os.path.exists(p) and verdict.search(open(p).read()):
            bad.append(f)
    neutrality_ok = all(
        "does not treat a change as good or bad" in open(os.path.join(OUT, f)).read()
        for f in ("00_NEW_HEAD_COACHES.md", "00_NEW_OFFENSIVE_COORDINATORS.md",
                  "00_NEW_DEFENSIVE_COORDINATORS.md", "00_NEW_PLAY_CALLERS.md",
                  "00_MAJOR_SCHEME_CHANGES.md", "00_HIGH_CONTINUITY_STAFFS.md",
                  "00_LOW_CONTINUITY_STAFFS.md"))
    check(not bad and neutrality_ok,
          "change indexes carry VSiN's assessment, not a TTW verdict",
          str(bad[:5]))

    # 9 -- every guide contradiction preserved, none silently resolved
    machine = coaching_conflicts(teams, stability, carousel)
    conf = open(os.path.join(OUT, "00_SOURCE_CONFLICTS.md")).read()
    missing = [c["team"] for c in machine if c["team"] not in conf]
    navy = "fourth season at the helm" in conf and "5th season" in conf
    rendered = [c["team"] for c in machine
                if "## SOURCE CONFLICT" not in text.get(c["team"], "")]
    check(not missing and navy and not rendered,
          f"all {len(machine)} machine conflicts preserved, Navy carried forward",
          f"missing {missing[:3]} unrendered {rendered[:3]}")

    # 10 -- indexes complete and Phase 4 untouched
    absent = [f for f in INDEXES if not os.path.exists(os.path.join(OUT, f))]
    qb_files = glob.glob("04_Quarterback_Database/*.md")
    crosslinked = sum(1 for t in teams
                      if f"../04_Quarterback_Database/{slug(t)}" in text.get(t, ""))
    check(not absent and len(qb_files) >= 139 and crosslinked == 138,
          "all 12 index files present; Phase 4 read and cross-linked, not written",
          f"absent {absent} qb_files {len(qb_files)} crosslinked {crosslinked}")

    print("PHASE 5 VALIDATION")
    print("=" * 60)
    for m in PASS:
        print(f"  PASS  {m}")
    for m in FAIL:
        print(f"  FAIL  {m}")
    print()
    if FAIL:
        print(f"{len(FAIL)} of {len(PASS) + len(FAIL)} checks failed")
        sys.exit(1)
    print(f"all {len(PASS)} checks passed")


if __name__ == "__main__":
    main()
